drop table if exsists member CASCADE;

create table member
(
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

insert into member (name) values ('spring2');
SELECT * FROM member;insert into member (name) values ('spring2');

SELECT * FROM member;